### PR TITLE
Update ckan role to work with ansible 2.x

### PR DESCRIPTION
**Pull request by mattboehm**
* variables passed to with-items can no longer be bare and must be in
  quotes/double-braces: `"{{myVariable}}"`

### CODE REVIEW

**Comment by mattboehm** [comment]
I confirmed with Frank that he has ansible 2.x installed, but it would still be good to check with other devs to see whether anyone uses 1.x and whether these changes break things for them.

**Comment by tanderegg** [comment]
@mattboehm We've been updating the https://github.com/cfpb/aurora code for Ansible 2.x, I think generally that's the way to go at this point, but @sleitner @JeffreyMFarley do you all have an opinion?

**Review by JeffreyMFarley — APPROVED** [review]
LGTM

**Comment by sleitner** [comment]
Yeah, I agree. devs should be upgrading if they're not already on 2.

**Pull request merged**
